name: Auto Merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Auto merge if tests pass and approvals are met
        id: merge
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github-token: ${{ secrets.GITHUB_TOKN }}
          merge-method: merge # Options are merge, squash, rebase
          commit-message: merge # Options are merge, title, pull-request-title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKN }}

      - name: Comment on PR
        if: steps.merge.outputs.pull-request-merged == 'true'
        run: |
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments -d '{"body": "This PR has been automatically merged."}'
